#!/bin/bash

current_color() {
  echo `osascript -s s -e "tell application \"iTerm\" to tell the current terminal to tell the current session to get its background color"`
}

set_color() {
  /usr/bin/osascript <<EOF
tell application "iTerm"
  tell the current terminal
    tell the current session
      set background color to $1
    end tell
  end tell
end tell
EOF
}

reset_color() {
  set_color "$previousColor"
}

with_bg() {
  if [ $3 != "" ]; then
    previousColor=`current_color`
    trap "reset_color" EXIT
    set_color "{$(($1*65535/255)), $(($2*65535/255)), $(($3*65535/255))}"
    shift;shift;shift
    eval $@
    reset_color
  fi
}

with_bg $@
